### ISSUE TITLE
Assertion fail when changing the screen Y size to 0

### ISSUE THREAD

**Issue by GamEsnitzhel** [DigiPen-Faculty/DigiPen-Graphics-Library#1]
When the user drags the screen Y size to 0, you get an assertion failure.

![image](https://user-images.githubusercontent.com/80675809/210939413-a84d13eb-814e-4ddb-83a0-a38c82aa8e00.png)

I'm currently trying to fix it, semi-unsuccessfully because I have to learn how making a window and also a .dll works.

**Comment by GamEsnitzhel** [comment]
I've found a solution using [WM_GETMINMAXINFO](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-getminmaxinfo?redirectedfrom=MSDN), but it is to be fair past midnight. I have a poorly written solution right now, when I wake up I'll fix it.

**Comment by GamEsnitzhel** [comment]
I fixed it in my build, however had to add a function to account for the titlebar size. I am not sure if I should submit a pull request or not, I plan on asking you next time I'm in class on Monday.

**Comment by AEllinger** [comment]
There's a quick fix for this, I'll include it in the next release. If you want to change it for yourself, what I'm doing is adding code in CameraObject::ResetWindowSize to return if the window X or Y size is <= 0 before calling gGraphics->D3D.ResetOnSizeChange().
